version: '3.8'

services:
  splunk_enterprise:
    build:
      context: splunk-enterprise
      args:
        - RELEASE_URL=7.3.6/linux/splunk-7.3.6-47d8552a4d84-Linux-x86_64.tgz
    ports:
      - "8000:8000"
    expose:
      - 9997
      - 8089

  universal_forwarder:
    build:
      context: universal-forwarder
      args:
        - RELEASE_URL=7.3.6/linux/splunkforwarder-7.3.6-47d8552a4d84-Linux-x86_64.tgz
    depends_on:
      - splunk_enterprise
